# This workflow will build the Gitblit project with Gradle

name: CI

on:
  push:
    branches-ignore:
      - 'release*'
      - gh-pages

jobs:
  build_linux:
    name: Build and unit test in Linux environment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [8, 11]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Java ${{ matrix.java-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      - name: Report Java version
        run: |
          java -version
          javac -version

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build all artifacts
        run: ./gradlew --no-daemon buildAll

      - name: Archive build artifacts (built in linux and by Java 8 only)
          if: ${{ matrix.java-version == 8 }}
        uses: actions/upload-artifact@v1
        with:
          name: build-artifacts-linux-java${{ matrix.java-version }}
          path: build\distributions

      - name: Run unit tests, excluding the Ldap*Test classes
        run: ./gradlew --no-daemon test -PexcludeTests=**/Ldap*Test.class

      - name: Archive test reports, excluding the Ldap*Test classes
        uses: actions/upload-artifact@v1
        with:
          name: test-reports-no-LdapTests-linux-java${{ matrix.java-version }}
          path: build\reports\tests

      - name: Run only the Ldap*Test unit tests
        run: ./gradlew --no-daemon test --tests *Ldap*Test

      - name: Archive test report for the Ldap*Test
        uses: actions/upload-artifact@v1
        with:
          name: test-report-for-LdapTests-linux-java${{ matrix.java-version }}
          path: build\reports\tests


  build_windows:
    name: Build and unit test in Windows environment
    runs-on: windows-latest
    strategy:
      matrix:
        java-version: [8, 11]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~\.gradle\caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Java ${{ matrix.java-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      - name: Report Java version
        run: |
          java -version
          javac -version

      - name: Build all artifacts
        run: .\gradlew.bat --no-daemon buildAll

      - name: Run unit tests, excluding the LdapPublicKeyManagerTest class
        run: .\gradlew.bat --no-daemon test -PexcludeTests=**/LdapPublicKeyManagerTest.class

      - name: Archive test reports, excluding LdapPublicKeyManagerTest
        uses: actions/upload-artifact@v1
        with:
          name: test-reports-no-LdapPublicKeyManagerTest-windows-java${{ matrix.java-version }}
          path: build\reports\tests

      - name: Archive code coverage reports, excluding LdapPublicKeyManagerTest
          if: ${{ matrix.java-version == 8 }}
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-reports-windows-java${{ matrix.java-version }}
          path: build\reports\jacoco

      - name: Run only the LdapPublicKeyManagerTest unit test class
        run: .\gradlew.bat --no-daemon test --tests *LdapPublicKeyManagerTest

      - name: Archive test report for LdapPublicKeyManagerTest
        uses: actions/upload-artifact@v1
        with:
          name: test-report-for-LdapPublicKeyManagerTest-windows-java${{ matrix.java-version }}
          path: build\reports\tests

      - name: Archive code coverage report for LdapPublicKeyManagerTest
          if: ${{ matrix.java-version == 8 }}
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report-for-LdapPublicKeyManagerTest-windows-java${{ matrix.java-version }}
          path: build\reports\jacoco

