# This workflow will build the Gitblit project with Gradle

name: CI

on:
  push:
    branches-ignore:
      - 'release*'
      - gh-pages

jobs:
  build_linux:
    name: Build and test in Linux environment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [8, 11]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Java ${{ matrix.java-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      - name: Report Java version
        run: |
          java -version
          javac -version

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build all artefacts
        run: ./gradlew --no-daemon buildAll

      - name: Run unit tests, excluding the Ldap*Test classes
        run: ./gradlew --no-daemon test -PexcludeTests=**/Ldap*Test.class

      - name: Run only the Ldap*Test unit tests
        run: ./gradlew --no-daemon test --tests *Ldap*Test

  build_windows:
    name: Build and test in Windows environment
    runs-on: windows-latest
    strategy:
      matrix:
        java-version: [8, 11]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~\.gradle\caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Java ${{ matrix.java-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      - name: Report Java version
        run: |
          java -version
          javac -version

      - name: Build all artefacts
        run: .\gradlew.bat --no-daemon buildAll

      - name: Run unit tests, excluding the LdapPublicKeyManagerTest class
        run: .\gradlew.bat --no-daemon test -PexcludeTests=**/LdapPublicKeyManagerTest.class

      - name: Run only the LdapPublicKeyManagerTest unit test class
        run: .\gradlew.bat --no-daemon test --tests *LdapPublicKeyManagerTest

